compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.1.1.cjs
